In [ ]:
from datasets.Femnist import Femnist
from graphs import SmallWorld
from collections import defaultdict
import os
import json
import numpy as np


In [ ]:
a = FEMNIST
a

In [ ]:
b = SmallWorld(6, 2, 2, 1)

In [ ]:
b.adj_list

In [ ]:
for i in range(12):
    print(b.neighbors(i))

In [ ]:
clients = []

In [ ]:
num_samples = []
data = defaultdict(lambda : None)

In [ ]:
datadir = "./leaf/data/femnist/data/train"
files = os.listdir(datadir)
total_users=0
users = set()

In [ ]:
files = os.listdir(datadir)[0:1]

In [ ]:
for f in files:
    file_path = os.path.join(datadir, f)
    print(file_path)
    with open(file_path, 'r') as inf:
        client_data = json.load(inf)
    current_users = len(client_data['users'])
    print("Current_Users: ", current_users)
    total_users += current_users
    users.update(client_data['users'])

print("total_users: ", total_users)
print("total_users: ", len(users))
print(client_data['user_data'].keys())
print(np.array(client_data['user_data']['f3408_47']['x']).shape)
print(np.array(client_data['user_data']['f3408_47']['y']).shape)
print(np.array(client_data['user_data']['f3327_11']['x']).shape)
print(np.array(client_data['user_data']['f3327_11']['y']).shape)
print(np.unique(np.array(client_data['user_data']['f3327_11']['y'])))

In [ ]:
file = 'run.py'
with open(file, 'r') as inf:
            print(inf.readline().strip())
            print(inf.readlines())

In [ ]:
def f(l):
    l[2] = 'c'

a = ['a', 'a', 'a']
print(a)
f(a)
print(a)

In [ ]:
l = ['a', 'b', 'c']
print(l[:-1])

In [ ]:
from localconfig import LocalConfig

def read_ini(file_path):
    config = LocalConfig(file_path)
    for section in config:
        print("Section: ", section)
        for key, value in config.items(section):
            print((key, value))
    print(dict(config.items('DATASET')))
 
read_ini("config.ini")

In [ ]:
def func(a = 1, b = 2, c = 3):
    print(a + b + c)

l = [3, 5, 7]

func(*l)

In [ ]:
from torch import multiprocessing as mp

mp.spawn(fn = func, nprocs = 2, args = [], kwargs = {'a': 4, 'b': 5, 'c': 6})

In [ ]:
l = '[0.4, 0.2, 0.3, 0.1]'
type(eval(l))



In [ ]:
f1 = Femnist(1, 'leaf/data/femnist/data/train')
f1.instantiate_dataset()
f1.train_x.shape

In [ ]:
from decentralizepy.datasets.Femnist import Femnist
from decentralizepy.graphs.SmallWorld import SmallWorld
from decentralizepy.mappings.Linear import Linear

f = Femnist(2, 'leaf/data/femnist/data/train', sizes=[0.6, 0.4])
g = SmallWorld(4, 1, 0.5)
l = Linear(2, 2)

In [ ]:
from decentralizepy.node.Node import Node
from torch import multiprocessing as mp
import logging
n1 = Node(0, l, g, f, "./results", logging.DEBUG)
n2 = Node(1, l, g, f, "./results", logging.DEBUG)
# mp.spawn(fn = Node, nprocs = 2, args=[l,g,f])

In [2]:
from testing import f

In [3]:
from torch import multiprocessing as mp
import torch
m1 = torch.nn.Linear(1,1)
o1 = torch.optim.SGD(m1.parameters(), 0.6)
print(m1)


mp.spawn(fn = f, nprocs = 2, args=[m1, o1])



Linear(in_features=1, out_features=1, bias=True)
1 OrderedDict([('weight', tensor([[0.9654]])), ('bias', tensor([-0.2141]))])
1 [{'params': [Parameter containing:
tensor([[0.9654]], requires_grad=True), Parameter containing:
tensor([-0.2141], requires_grad=True)], 'lr': 0.6, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False}]
1 OrderedDict([('weight', tensor([[0.]])), ('bias', tensor([-0.2141]))])
1 [{'params': [Parameter containing:
tensor([[0.]], requires_grad=True), Parameter containing:
tensor([-0.2141], requires_grad=True)], 'lr': 0.6, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False}]
0 OrderedDict([('weight', tensor([[0.]])), ('bias', tensor([-0.2141]))])
0 [{'params': [Parameter containing:
tensor([[0.]], requires_grad=True), Parameter containing:
tensor([-0.2141], requires_grad=True)], 'lr': 0.6, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False}]
0 OrderedDict([('weight', tensor([[0.]])), ('bias', tensor([-0.2141]))])
0 [

In [ ]:
o1.param_groups

In [ ]:
with torch.no_grad():
    o1.param_groups[0]["params"][0].copy_(torch.zeros(1,))

In [ ]:
o1.param_groups

In [ ]:
m1.state_dict()