In [ ]:
from datasets.Femnist import Femnist
from graphs import SmallWorld
from collections import defaultdict
import os
import json
import numpy as np


In [ ]:
a = FEMNIST
a

In [ ]:
b = SmallWorld(6, 2, 2, 1)

In [ ]:
b.adj_list

In [ ]:
for i in range(12):
    print(b.neighbors(i))

In [ ]:
clients = []

In [ ]:
num_samples = []
data = defaultdict(lambda : None)

In [ ]:
datadir = "./leaf/data/femnist/data/train"
files = os.listdir(datadir)
total_users=0
users = set()

In [ ]:
files = os.listdir(datadir)[0:1]

In [ ]:
for f in files:
    file_path = os.path.join(datadir, f)
    print(file_path)
    with open(file_path, 'r') as inf:
        client_data = json.load(inf)
    current_users = len(client_data['users'])
    print("Current_Users: ", current_users)
    total_users += current_users
    users.update(client_data['users'])

print("total_users: ", total_users)
print("total_users: ", len(users))
print(client_data['user_data'].keys())
print(np.array(client_data['user_data']['f3408_47']['x']).shape)
print(np.array(client_data['user_data']['f3408_47']['y']).shape)
print(np.array(client_data['user_data']['f3327_11']['x']).shape)
print(np.array(client_data['user_data']['f3327_11']['y']).shape)
print(np.unique(np.array(client_data['user_data']['f3327_11']['y'])))

In [ ]:
file = 'run.py'
with open(file, 'r') as inf:
            print(inf.readline().strip())
            print(inf.readlines())

In [ ]:
def f(l):
    l[2] = 'c'

a = ['a', 'a', 'a']
print(a)
f(a)
print(a)

In [ ]:
l = ['a', 'b', 'c']
print(l[:-1])

In [ ]:
from localconfig import LocalConfig

def read_ini(file_path):
    config = LocalConfig(file_path)
    for section in config:
        print("Section: ", section)
        for key, value in config.items(section):
            print((key, value))
    print(dict(config.items('DATASET')))
    return config
 
config = read_ini("config.ini")
for section in config:
    print(section)
#d = dict(config.sections())

In [ ]:
def func(a = 1, b = 2, c = 3):
    print(a + b + c)

l = [3, 5, 7]

func(*l)

In [ ]:
from torch import multiprocessing as mp

mp.spawn(fn = func, nprocs = 2, args = [], kwargs = {'a': 4, 'b': 5, 'c': 6})

In [ ]:
l = '[0.4, 0.2, 0.3, 0.1]'
type(eval(l))



In [ ]:
from decentralizepy.datasets.Femnist import Femnist
f1 = Femnist(0, 1, 'leaf/data/femnist/data/train')
ts = f1.get_trainset(1)
for data, target in ts:
    print(data)
    break

In [ ]:
from decentralizepy.datasets.Femnist import Femnist
from decentralizepy.graphs.SmallWorld import SmallWorld
from decentralizepy.mappings.Linear import Linear

f = Femnist(2, 'leaf/data/femnist/data/train', sizes=[0.6, 0.4])
g = SmallWorld(4, 1, 0.5)
l = Linear(2, 2)

In [ ]:
from decentralizepy.node.Node import Node
from torch import multiprocessing as mp
import logging
n1 = Node(0, l, g, f, "./results", logging.DEBUG)
n2 = Node(1, l, g, f, "./results", logging.DEBUG)
# mp.spawn(fn = Node, nprocs = 2, args=[l,g,f])

In [ ]:
from testing import f

In [ ]:
from torch import multiprocessing as mp
import torch
m1 = torch.nn.Linear(1,1)
o1 = torch.optim.SGD(m1.parameters(), 0.6)
print(m1)


mp.spawn(fn = f, nprocs = 2, args=[m1, o1])



In [ ]:
o1.param_groups

In [ ]:
with torch.no_grad():
    o1.param_groups[0]["params"][0].copy_(torch.zeros(1,))

In [ ]:
o1.param_groups

In [ ]:
m1.state_dict()

In [ ]:
import torch
loss = getattr(torch.nn.functional, 'nll_loss')

In [ ]:
loss

In [2]:
%matplotlib inline

from decentralizepy.node.Node import Node
from decentralizepy.graphs.SmallWorld import SmallWorld
from decentralizepy.graphs.Graph import Graph
from decentralizepy.mappings.Linear import Linear
from torch import multiprocessing as mp
import torch
import logging

from localconfig import LocalConfig

def read_ini(file_path):
    config = LocalConfig(file_path)
    for section in config:
        print("Section: ", section)
        for key, value in config.items(section):
            print((key, value))
    print(dict(config.items('DATASET')))
    return config
 
config = read_ini("config.ini")
my_config = dict()
for section in config:
    my_config[section] = dict(config.items(section))

#f = Femnist(2, 'leaf/data/femnist/data/train', sizes=[0.6, 0.4])
g = Graph()
g.read_graph_from_file("36_nodes.edges", "edges")
l = Linear(1, 36)

#Node(0, 0, l, g, my_config, 20, "results", logging.DEBUG)

mp.spawn(fn = Node, nprocs = g.n_procs, args=[0,l,g,my_config,20,"results",logging.INFO])

# mp.spawn(fn = Node, args = [l, g, config, 10, "results", logging.DEBUG], nprocs=2)


Section:  GRAPH
('package', 'decentralizepy.graphs.SmallWorld')
('graph_class', 'SmallWorld')
Section:  DATASET
('dataset_package', 'decentralizepy.datasets.Femnist')
('dataset_class', 'Femnist')
('model_class', 'CNN')
('n_procs', 36)
('train_dir', 'leaf/data/femnist/per_user_data/train')
('test_dir', 'leaf/data/femnist/data/test')
('sizes', '')
Section:  OPTIMIZER_PARAMS
('optimizer_package', 'torch.optim')
('optimizer_class', 'Adam')
('lr', 0.01)
Section:  TRAIN_PARAMS
('training_package', 'decentralizepy.training.Training')
('training_class', 'Training')
('epochs_per_round', 1)
('batch_size', 1024)
('shuffle', True)
('loss_package', 'torch.nn')
('loss_class', 'CrossEntropyLoss')
Section:  COMMUNICATION
('comm_package', 'decentralizepy.communication.TCP')
('comm_class', 'TCP')
('addresses_filepath', 'ip_addr.json')
Section:  SHARING
('sharing_package', 'decentralizepy.sharing.Sharing')
('sharing_class', 'Sharing')
{'dataset_package': 'decentralizepy.datasets.Femnist', 'dataset_class'

In [ ]:
from decentralizepy.mappings.Linear import Linear
from testing import f
from torch import multiprocessing as mp

l = Linear(1, 2)
mp.spawn(fn = f, nprocs = 2, args = [0, 2, "ip_addr.json", l])


In [ ]:
from decentralizepy.datasets.Femnist import Femnist

f = Femnist()

f.file_per_user('../leaf/data/femnist/data/train','../leaf/data/femnist/per_user_data/train')


In [2]:
a = set()
a.update([2, 3, 4, 5])

In [3]:
a

{2, 3, 4, 5}

In [5]:
print(*a)

2 3 4 5


In [3]:
from decentralizepy.graphs.FullyConnected import FullyConnected

s = FullyConnected(96)
s.write_graph_to_file('96_node_fullyConnected.edges')

In [2]:
from decentralizepy.graphs.SmallWorld import SmallWorld

s = SmallWorld(96, 2, .5)
s.write_graph_to_file('96_nodes.edges')

In [1]:
import sys
sys.argv

['/home/risharma/miniconda3/envs/decpy/lib/python3.9/site-packages/ipykernel_launcher.py',
 '--ip=127.0.0.1',
 '--stdin=9008',
 '--control=9006',
 '--hb=9005',
 '--Session.signature_scheme="hmac-sha256"',
 '--Session.key=b"eac5d2f8-c460-45f1-a268-1e4b46a6efd6"',
 '--shell=9007',
 '--transport="tcp"',
 '--iopub=9009',
 '--f=/tmp/tmp-21212479paJaUBJBN84.json']

In [24]:
import torch
from decentralizepy.datasets.Femnist import CNN
m1 = CNN()
o1 = torch.optim.SGD(m1.parameters(), 0.6)
#print("m1_parameters: ", {k:v.data for k, v in zip(m1.state_dict(), m1.parameters())})
#print("m1_state_dict: ", m1.state_dict())
#print("o1_state_dict: ", o1.state_dict())
tensors_to_cat = [v.data for _, v in m1.state_dict().items()]
print("tensors to cat: ", tensors_to_cat)


tensors to cat:  [tensor([[[[-0.0754, -0.1052,  0.0336,  0.0976, -0.1882],
          [ 0.1723,  0.0860, -0.0557, -0.1182,  0.1845],
          [-0.1112,  0.0554, -0.0190,  0.1264, -0.0851],
          [-0.0788,  0.1281, -0.0477,  0.1910,  0.0089],
          [-0.1205, -0.0230, -0.0574,  0.1633, -0.1101]]],


        [[[ 0.0271, -0.1426, -0.0381,  0.1128,  0.0396],
          [-0.0023,  0.1021, -0.0483, -0.0167,  0.0090],
          [-0.0645, -0.1863, -0.1494, -0.0473,  0.1572],
          [-0.0027, -0.0923,  0.0186,  0.0787,  0.1404],
          [ 0.0714,  0.0434,  0.1853,  0.1262,  0.0502]]],


        [[[-0.1708,  0.0628, -0.1877, -0.0879, -0.1190],
          [-0.0111,  0.0684, -0.1659, -0.1297,  0.0684],
          [ 0.1629, -0.1196, -0.0096,  0.1854, -0.0721],
          [ 0.1122, -0.0325,  0.1887, -0.0685,  0.1441],
          [ 0.1734,  0.0720, -0.0941, -0.0536,  0.0355]]],


        [[[-0.1465, -0.0899,  0.1122,  0.0323, -0.1287],
          [-0.1237,  0.0852, -0.1984, -0.0995,  0.0734],
 

In [25]:
a = [(3, 2), (2, 5), (2, 6)]
#a.sort(reverse = True)


In [26]:
b = [(13, 12), (12, 15), (12, 16)]

import torch
a_t = torch.tensor(a)
b_t = torch.tensor(b)

In [27]:
print(a_t)
print(b_t)

tensor([[3, 2],
        [2, 5],
        [2, 6]])
tensor([[13, 12],
        [12, 15],
        [12, 16]])


In [31]:
indices = torch.tensor([2, 3, 5])
torch.flatten(a_t)[indices] = torch.flatten(b_t)[:3]

In [15]:
c = torch.stack((torch.flatten(a_t), torch.flatten(b_t)), dim=-1)

In [32]:
print(a_t)
print(b_t)

tensor([[ 3,  2],
        [13, 12],
        [ 2, 12]])
tensor([[13, 12],
        [12, 15],
        [12, 16]])


In [16]:
c

tensor([[ 3, 13],
        [ 2, 12],
        [ 2, 12],
        [ 5, 15],
        [ 2, 12],
        [ 6, 16]])

In [7]:
c[-1] = 26

In [8]:
c

tensor([ 3,  2,  2,  5,  2,  6, 13, 12, 12, 15, 12, 26])

In [9]:
b

[(13, 12), (12, 15), (12, 16)]

In [34]:
torch.tensor([1,2,3]).shape[0]

3